image:
  name: docker:stable

services:
  - name: docker:dind
    alias: dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://dind:2375
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

stages:
  - build
  - test
  - deploy

before_script:
  - docker info

build-job:
  stage: build
  script:
    - echo "build job"

test-job:
  stage: test
  script:
    - echo "test job"

deploy-job:
  stage: deploy
  script:
    - echo "deploy job"
