version: "3"
services:
  app:
    build:
      context: .
    container_name: app
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app"
